### Create Study Card
POST {{BaseUrl}}/api/v1/study/create
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "title": "This is Study 10",
  "dueDate": "2025-08-20",
  "content": "Detailed content of the study card",
  "maxParticipants": 10,
  "category": "HOBBY",
  "isOnline": true
}

### Delete Study Card
DELETE {{BaseUrl}}/api/v1/study/delete/{{StudyCardId}}
Authorization: Bearer {{AccessToken}}

### Get Study Card List
GET {{BaseUrl}}/api/v1/study/list?available=true&page=0
Authorization: Bearer {{AccessToken}}

### Apply Study
POST {{BaseUrl}}/api/v1/study/apply
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "studyCardId": "{{StudyCardId}}"
}

### Cancel Study Application
POST {{BaseUrl}}/api/v1/study/cancel
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "studyCardId": "{{StudyCardId}}"
}