### Create Study Card
POST {{BaseUrl}}/api/v1/study/create
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "title": "This is Study 10",
  "dueDate": "2025-08-20",
  "content": "Detailed content of the study card",
  "maxParticipants": 10,
  "category": "HOBBY",
  "isOnline": true
}

### Delete Study Card
DELETE {{BaseUrl}}/api/v1/study/delete/{{StudyCardId}}
Authorization: Bearer {{AccessToken}}

### Get Study Card List
GET {{BaseUrl}}/api/v1/study/list?available=false&page=0&size=3
Authorization: Bearer {{AccessToken}}